# Generated by Django 5.1.1 on 2024-09-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_coddetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coddetails',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coddetails',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='coddetails',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
