# Generated by Django 5.1.1 on 2024-09-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_remove_coddetails_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coddetails',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coddetails',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
